// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package MSG is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	common.proto
	game.proto
	login.proto

It has these top-level messages:
	ChatReq
	ChatAns
	ChatNot
	CreateChatRoomReq
	CreateChatRoomAns
	InviteChatRoomReq
	InviteChatRoomAns
	InviteChatRoomNot
	EnterChatRoomReq
	EnterChatRoomAns
	EnterChatRoomNot
	LeaveChatRoomReq
	LeaveChatRoomAns
	LeaveChatRoomNot
	CharData_
	UserData_
	Contents_
	GMember_
	Group_
	ChatData_
	ChatRoom_
	ChatChannel_
	DungeonData_
	BattleData_
	ContentsNot
	PlayDungeonNot
	OwnedCharacterNot
	CreateCharReq
	CreateCharAns
	CurrencyNot
	PlayDungeonReq
	PlayDungeonAns
	LevelupCharReq
	LevelupCharAns
	TierupCharReq
	TierupCharAns
	PingReq
	PongAns
	LoginReq
	LoginAns
	RegistReq
	RegistAns
	VersionReq
	VersionAns
*/
package MSG

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// chat
type ChatReq struct {
	Msg              *string   `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	Type             *ChatType `protobuf:"varint,2,req,name=type,enum=MSG.ChatType" json:"type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ChatReq) Reset()                    { *m = ChatReq{} }
func (m *ChatReq) String() string            { return proto.CompactTextString(m) }
func (*ChatReq) ProtoMessage()               {}
func (*ChatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatReq) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *ChatReq) GetType() ChatType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ChatType_CHAT_CHANNEL
}

type ChatAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ChatAns) Reset()                    { *m = ChatAns{} }
func (m *ChatAns) String() string            { return proto.CompactTextString(m) }
func (*ChatAns) ProtoMessage()               {}
func (*ChatAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type ChatNot struct {
	Chats            *ChatData_ `protobuf:"bytes,1,req,name=chats" json:"chats,omitempty"`
	Type             *ChatType  `protobuf:"varint,2,req,name=type,enum=MSG.ChatType" json:"type,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ChatNot) Reset()                    { *m = ChatNot{} }
func (m *ChatNot) String() string            { return proto.CompactTextString(m) }
func (*ChatNot) ProtoMessage()               {}
func (*ChatNot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatNot) GetChats() *ChatData_ {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *ChatNot) GetType() ChatType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ChatType_CHAT_CHANNEL
}

// create chat room
type CreateChatRoomReq struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Greeting         *string `protobuf:"bytes,2,req,name=greeting" json:"greeting,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateChatRoomReq) Reset()                    { *m = CreateChatRoomReq{} }
func (m *CreateChatRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CreateChatRoomReq) ProtoMessage()               {}
func (*CreateChatRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateChatRoomReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateChatRoomReq) GetGreeting() string {
	if m != nil && m.Greeting != nil {
		return *m.Greeting
	}
	return ""
}

type CreateChatRoomAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	Rid              *uint64    `protobuf:"varint,2,opt,name=rid" json:"rid,omitempty"`
	Rkey             *string    `protobuf:"bytes,3,opt,name=rkey" json:"rkey,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CreateChatRoomAns) Reset()                    { *m = CreateChatRoomAns{} }
func (m *CreateChatRoomAns) String() string            { return proto.CompactTextString(m) }
func (*CreateChatRoomAns) ProtoMessage()               {}
func (*CreateChatRoomAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateChatRoomAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

func (m *CreateChatRoomAns) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *CreateChatRoomAns) GetRkey() string {
	if m != nil && m.Rkey != nil {
		return *m.Rkey
	}
	return ""
}

// invite chat room
type InviteChatRoomReq struct {
	// room info
	Rid  *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Rkey *string `protobuf:"bytes,2,req,name=rkey" json:"rkey,omitempty"`
	// invite target info
	TargetUid        *uint64 `protobuf:"varint,3,req,name=targetUid" json:"targetUid,omitempty"`
	TargetName       *string `protobuf:"bytes,4,req,name=targetName" json:"targetName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InviteChatRoomReq) Reset()                    { *m = InviteChatRoomReq{} }
func (m *InviteChatRoomReq) String() string            { return proto.CompactTextString(m) }
func (*InviteChatRoomReq) ProtoMessage()               {}
func (*InviteChatRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InviteChatRoomReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *InviteChatRoomReq) GetRkey() string {
	if m != nil && m.Rkey != nil {
		return *m.Rkey
	}
	return ""
}

func (m *InviteChatRoomReq) GetTargetUid() uint64 {
	if m != nil && m.TargetUid != nil {
		return *m.TargetUid
	}
	return 0
}

func (m *InviteChatRoomReq) GetTargetName() string {
	if m != nil && m.TargetName != nil {
		return *m.TargetName
	}
	return ""
}

type InviteChatRoomAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *InviteChatRoomAns) Reset()                    { *m = InviteChatRoomAns{} }
func (m *InviteChatRoomAns) String() string            { return proto.CompactTextString(m) }
func (*InviteChatRoomAns) ProtoMessage()               {}
func (*InviteChatRoomAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InviteChatRoomAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type InviteChatRoomNot struct {
	// room info
	Rid  *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Rkey *string `protobuf:"bytes,2,req,name=rkey" json:"rkey,omitempty"`
	// room owner info
	OwnerUid         *uint64 `protobuf:"varint,3,req,name=ownerUid" json:"ownerUid,omitempty"`
	OwnerName        *string `protobuf:"bytes,4,req,name=ownerName" json:"ownerName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InviteChatRoomNot) Reset()                    { *m = InviteChatRoomNot{} }
func (m *InviteChatRoomNot) String() string            { return proto.CompactTextString(m) }
func (*InviteChatRoomNot) ProtoMessage()               {}
func (*InviteChatRoomNot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InviteChatRoomNot) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *InviteChatRoomNot) GetRkey() string {
	if m != nil && m.Rkey != nil {
		return *m.Rkey
	}
	return ""
}

func (m *InviteChatRoomNot) GetOwnerUid() uint64 {
	if m != nil && m.OwnerUid != nil {
		return *m.OwnerUid
	}
	return 0
}

func (m *InviteChatRoomNot) GetOwnerName() string {
	if m != nil && m.OwnerName != nil {
		return *m.OwnerName
	}
	return ""
}

// enter chat room
type EnterChatRoomReq struct {
	// room info
	Rid              *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Rkey             *string `protobuf:"bytes,2,req,name=rkey" json:"rkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterChatRoomReq) Reset()                    { *m = EnterChatRoomReq{} }
func (m *EnterChatRoomReq) String() string            { return proto.CompactTextString(m) }
func (*EnterChatRoomReq) ProtoMessage()               {}
func (*EnterChatRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EnterChatRoomReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *EnterChatRoomReq) GetRkey() string {
	if m != nil && m.Rkey != nil {
		return *m.Rkey
	}
	return ""
}

type EnterChatRoomAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnterChatRoomAns) Reset()                    { *m = EnterChatRoomAns{} }
func (m *EnterChatRoomAns) String() string            { return proto.CompactTextString(m) }
func (*EnterChatRoomAns) ProtoMessage()               {}
func (*EnterChatRoomAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EnterChatRoomAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type EnterChatRoomNot struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterChatRoomNot) Reset()                    { *m = EnterChatRoomNot{} }
func (m *EnterChatRoomNot) String() string            { return proto.CompactTextString(m) }
func (*EnterChatRoomNot) ProtoMessage()               {}
func (*EnterChatRoomNot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EnterChatRoomNot) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *EnterChatRoomNot) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// leave chat room
type LeaveChatRoomReq struct {
	// room info
	Rid              *uint64 `protobuf:"varint,1,req,name=rid" json:"rid,omitempty"`
	Rkey             *string `protobuf:"bytes,2,req,name=rkey" json:"rkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveChatRoomReq) Reset()                    { *m = LeaveChatRoomReq{} }
func (m *LeaveChatRoomReq) String() string            { return proto.CompactTextString(m) }
func (*LeaveChatRoomReq) ProtoMessage()               {}
func (*LeaveChatRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LeaveChatRoomReq) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *LeaveChatRoomReq) GetRkey() string {
	if m != nil && m.Rkey != nil {
		return *m.Rkey
	}
	return ""
}

type LeaveChatRoomAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LeaveChatRoomAns) Reset()                    { *m = LeaveChatRoomAns{} }
func (m *LeaveChatRoomAns) String() string            { return proto.CompactTextString(m) }
func (*LeaveChatRoomAns) ProtoMessage()               {}
func (*LeaveChatRoomAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *LeaveChatRoomAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type LeaveChatRoomNot struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveChatRoomNot) Reset()                    { *m = LeaveChatRoomNot{} }
func (m *LeaveChatRoomNot) String() string            { return proto.CompactTextString(m) }
func (*LeaveChatRoomNot) ProtoMessage()               {}
func (*LeaveChatRoomNot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LeaveChatRoomNot) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LeaveChatRoomNot) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatReq)(nil), "MSG.ChatReq")
	proto.RegisterType((*ChatAns)(nil), "MSG.ChatAns")
	proto.RegisterType((*ChatNot)(nil), "MSG.ChatNot")
	proto.RegisterType((*CreateChatRoomReq)(nil), "MSG.CreateChatRoomReq")
	proto.RegisterType((*CreateChatRoomAns)(nil), "MSG.CreateChatRoomAns")
	proto.RegisterType((*InviteChatRoomReq)(nil), "MSG.InviteChatRoomReq")
	proto.RegisterType((*InviteChatRoomAns)(nil), "MSG.InviteChatRoomAns")
	proto.RegisterType((*InviteChatRoomNot)(nil), "MSG.InviteChatRoomNot")
	proto.RegisterType((*EnterChatRoomReq)(nil), "MSG.EnterChatRoomReq")
	proto.RegisterType((*EnterChatRoomAns)(nil), "MSG.EnterChatRoomAns")
	proto.RegisterType((*EnterChatRoomNot)(nil), "MSG.EnterChatRoomNot")
	proto.RegisterType((*LeaveChatRoomReq)(nil), "MSG.LeaveChatRoomReq")
	proto.RegisterType((*LeaveChatRoomAns)(nil), "MSG.LeaveChatRoomAns")
	proto.RegisterType((*LeaveChatRoomNot)(nil), "MSG.LeaveChatRoomNot")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0x6b, 0xea, 0x40,
	0x10, 0xc6, 0x24, 0x8f, 0xa7, 0xf3, 0xde, 0x13, 0xdd, 0x53, 0x90, 0x47, 0x49, 0x97, 0x1e, 0x84,
	0x82, 0x07, 0x69, 0xa1, 0xa7, 0x42, 0x49, 0x45, 0x0a, 0xd5, 0xc3, 0xda, 0x9e, 0x7a, 0x28, 0x8b,
	0x0e, 0x31, 0x94, 0x64, 0xed, 0x66, 0x55, 0xfc, 0xf7, 0x65, 0x36, 0xc1, 0x68, 0x4e, 0xdb, 0xde,
	0x66, 0x67, 0xbe, 0x6f, 0xbe, 0xef, 0xdb, 0x5d, 0x80, 0xe5, 0x5a, 0x9a, 0xd1, 0x46, 0x2b, 0xa3,
	0x98, 0x3f, 0x5b, 0x4c, 0x07, 0x7f, 0x97, 0x2a, 0xcb, 0x54, 0x5e, 0xb6, 0xf8, 0x3d, 0xfc, 0x8e,
	0xd7, 0xd2, 0x08, 0xfc, 0x64, 0x3d, 0xf0, 0xb3, 0x22, 0x09, 0x5b, 0x91, 0x37, 0xec, 0x08, 0x2a,
	0xd9, 0x25, 0x04, 0xe6, 0xb0, 0xc1, 0xd0, 0x8b, 0xbc, 0x61, 0x77, 0xfc, 0x6f, 0x34, 0x5b, 0x4c,
	0x47, 0x84, 0x7e, 0x39, 0x6c, 0x50, 0xd8, 0x11, 0xbf, 0x2e, 0xf9, 0x0f, 0x79, 0xc1, 0x22, 0xf0,
	0x51, 0x6b, 0xcb, 0xef, 0x8e, 0xbb, 0x16, 0x3c, 0xd1, 0x5a, 0xe9, 0x58, 0xad, 0x50, 0xd0, 0x88,
	0x8b, 0x12, 0x3c, 0x57, 0x86, 0x5d, 0xc1, 0x2f, 0x32, 0x56, 0x58, 0xf8, 0x9f, 0x0a, 0x4e, 0xc3,
	0x47, 0x69, 0xe4, 0xbb, 0x28, 0x87, 0x2e, 0x06, 0x62, 0xe8, 0xc7, 0x1a, 0xa5, 0x41, 0x1b, 0x43,
	0xa9, 0x8c, 0xa2, 0x30, 0x08, 0x72, 0x99, 0x61, 0x95, 0xc5, 0xd6, 0x6c, 0x00, 0xed, 0x44, 0x23,
	0x9a, 0x34, 0x4f, 0xec, 0xbe, 0x8e, 0x38, 0x9e, 0xf9, 0x5b, 0x73, 0x89, 0x53, 0x1e, 0xba, 0x31,
	0x9d, 0xae, 0x42, 0x2f, 0x6a, 0x0d, 0x03, 0x41, 0x25, 0x09, 0xeb, 0x0f, 0x3c, 0x84, 0x7e, 0xd4,
	0x22, 0x61, 0xaa, 0xf9, 0x1e, 0xfa, 0x4f, 0xf9, 0x2e, 0x3d, 0x77, 0x58, 0x51, 0x69, 0x79, 0x83,
	0x5a, 0x7a, 0xb3, 0x35, 0xfb, 0x0f, 0x1d, 0x23, 0x75, 0x82, 0xe6, 0x35, 0x5d, 0x85, 0xbe, 0xc5,
	0xd6, 0x0d, 0x76, 0x01, 0x50, 0x1e, 0xe6, 0x94, 0x35, 0xb0, 0xbc, 0x93, 0x0e, 0xbf, 0x6d, 0x0a,
	0xbb, 0xbd, 0x52, 0xd1, 0xa4, 0xd1, 0x7b, 0xb9, 0xf9, 0x1d, 0x40, 0x5b, 0xed, 0x73, 0xd4, 0xb5,
	0xdd, 0xe3, 0x99, 0xb2, 0xd8, 0xfa, 0xc4, 0x6c, 0xdd, 0xe0, 0x77, 0xd0, 0x9b, 0xe4, 0x06, 0xf5,
	0xb7, 0xef, 0x88, 0xdf, 0x34, 0x98, 0x6e, 0x21, 0x9b, 0x7a, 0x55, 0xc6, 0x6d, 0xad, 0xb7, 0x2d,
	0xf5, 0xec, 0x3f, 0xf2, 0xea, 0x7f, 0x44, 0xcc, 0x67, 0x94, 0x3b, 0xfc, 0x91, 0xd3, 0x33, 0xa6,
	0xb3, 0xd3, 0x33, 0x96, 0xb3, 0xd3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x06, 0x45, 0x6d,
	0xfb, 0x03, 0x00, 0x00,
}
