// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

package MSG

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 컨텐츠 정보 통보
type ContentsNot struct {
	Contents []string `protobuf:"bytes,1,rep,name=contents" json:"contents,omitempty"`
	// 마지막 던전 플레이 정보
	DungeonNo        *uint32 `protobuf:"varint,2,req,name=dungeonNo" json:"dungeonNo,omitempty"`
	Tier             *uint32 `protobuf:"varint,3,req,name=tier" json:"tier,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContentsNot) Reset()                    { *m = ContentsNot{} }
func (m *ContentsNot) String() string            { return proto.CompactTextString(m) }
func (*ContentsNot) ProtoMessage()               {}
func (*ContentsNot) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ContentsNot) GetContents() []string {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *ContentsNot) GetDungeonNo() uint32 {
	if m != nil && m.DungeonNo != nil {
		return *m.DungeonNo
	}
	return 0
}

func (m *ContentsNot) GetTier() uint32 {
	if m != nil && m.Tier != nil {
		return *m.Tier
	}
	return 0
}

// 휴식중 플레이 통보(1시간 1회 플레이)
type PlayDungeonNot struct {
	Plays            []*PlayDungeonNot_DungeonPlay `protobuf:"bytes,1,rep,name=plays" json:"plays,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PlayDungeonNot) Reset()                    { *m = PlayDungeonNot{} }
func (m *PlayDungeonNot) String() string            { return proto.CompactTextString(m) }
func (*PlayDungeonNot) ProtoMessage()               {}
func (*PlayDungeonNot) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *PlayDungeonNot) GetPlays() []*PlayDungeonNot_DungeonPlay {
	if m != nil {
		return m.Plays
	}
	return nil
}

type PlayDungeonNot_DungeonPlay struct {
	DungeonNo        *uint32        `protobuf:"varint,1,req,name=dungeonNo" json:"dungeonNo,omitempty"`
	Tier             *uint32        `protobuf:"varint,2,req,name=tier" json:"tier,omitempty"`
	Battles          []*BattleData_ `protobuf:"bytes,3,rep,name=battles" json:"battles,omitempty"`
	Chars            []*CharData_   `protobuf:"bytes,4,rep,name=chars" json:"chars,omitempty"`
	Mobs             []*CharData_   `protobuf:"bytes,5,rep,name=mobs" json:"mobs,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayDungeonNot_DungeonPlay) Reset()                    { *m = PlayDungeonNot_DungeonPlay{} }
func (m *PlayDungeonNot_DungeonPlay) String() string            { return proto.CompactTextString(m) }
func (*PlayDungeonNot_DungeonPlay) ProtoMessage()               {}
func (*PlayDungeonNot_DungeonPlay) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

func (m *PlayDungeonNot_DungeonPlay) GetDungeonNo() uint32 {
	if m != nil && m.DungeonNo != nil {
		return *m.DungeonNo
	}
	return 0
}

func (m *PlayDungeonNot_DungeonPlay) GetTier() uint32 {
	if m != nil && m.Tier != nil {
		return *m.Tier
	}
	return 0
}

func (m *PlayDungeonNot_DungeonPlay) GetBattles() []*BattleData_ {
	if m != nil {
		return m.Battles
	}
	return nil
}

func (m *PlayDungeonNot_DungeonPlay) GetChars() []*CharData_ {
	if m != nil {
		return m.Chars
	}
	return nil
}

func (m *PlayDungeonNot_DungeonPlay) GetMobs() []*CharData_ {
	if m != nil {
		return m.Mobs
	}
	return nil
}

// 보유중인 캐릭터 리스트 통보
type OwnedCharacterNot struct {
	Chars            []*CharData_ `protobuf:"bytes,1,rep,name=chars" json:"chars,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *OwnedCharacterNot) Reset()                    { *m = OwnedCharacterNot{} }
func (m *OwnedCharacterNot) String() string            { return proto.CompactTextString(m) }
func (*OwnedCharacterNot) ProtoMessage()               {}
func (*OwnedCharacterNot) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *OwnedCharacterNot) GetChars() []*CharData_ {
	if m != nil {
		return m.Chars
	}
	return nil
}

// 캐릭터 생성( 캐릭터가 존재하지 않으면 무료 1개 캐릭터 생성 가능)
type CreateCharReq struct {
	CharNo           *uint32 `protobuf:"varint,1,req,name=charNo" json:"charNo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateCharReq) Reset()                    { *m = CreateCharReq{} }
func (m *CreateCharReq) String() string            { return proto.CompactTextString(m) }
func (*CreateCharReq) ProtoMessage()               {}
func (*CreateCharReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CreateCharReq) GetCharNo() uint32 {
	if m != nil && m.CharNo != nil {
		return *m.CharNo
	}
	return 0
}

type CreateCharAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CreateCharAns) Reset()                    { *m = CreateCharAns{} }
func (m *CreateCharAns) String() string            { return proto.CompactTextString(m) }
func (*CreateCharAns) ProtoMessage()               {}
func (*CreateCharAns) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *CreateCharAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

// 재화 변화 통보
type CurrencyNot struct {
	Vc1              *uint32 `protobuf:"varint,1,req,name=vc1" json:"vc1,omitempty"`
	Vc2              *uint32 `protobuf:"varint,2,req,name=vc2" json:"vc2,omitempty"`
	Vc3              *uint32 `protobuf:"varint,3,req,name=vc3" json:"vc3,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CurrencyNot) Reset()                    { *m = CurrencyNot{} }
func (m *CurrencyNot) String() string            { return proto.CompactTextString(m) }
func (*CurrencyNot) ProtoMessage()               {}
func (*CurrencyNot) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *CurrencyNot) GetVc1() uint32 {
	if m != nil && m.Vc1 != nil {
		return *m.Vc1
	}
	return 0
}

func (m *CurrencyNot) GetVc2() uint32 {
	if m != nil && m.Vc2 != nil {
		return *m.Vc2
	}
	return 0
}

func (m *CurrencyNot) GetVc3() uint32 {
	if m != nil && m.Vc3 != nil {
		return *m.Vc3
	}
	return 0
}

// 던전 플레이 요청
type PlayDungeonReq struct {
	DungeonNo        *uint32 `protobuf:"varint,1,req,name=dungeonNo" json:"dungeonNo,omitempty"`
	Tier             *uint32 `protobuf:"varint,2,req,name=tier" json:"tier,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayDungeonReq) Reset()                    { *m = PlayDungeonReq{} }
func (m *PlayDungeonReq) String() string            { return proto.CompactTextString(m) }
func (*PlayDungeonReq) ProtoMessage()               {}
func (*PlayDungeonReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *PlayDungeonReq) GetDungeonNo() uint32 {
	if m != nil && m.DungeonNo != nil {
		return *m.DungeonNo
	}
	return 0
}

func (m *PlayDungeonReq) GetTier() uint32 {
	if m != nil && m.Tier != nil {
		return *m.Tier
	}
	return 0
}

// 던전 플레이 결과
type PlayDungeonAns struct {
	Err *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	// 던전 플레이 결과
	Battles          []*BattleData_ `protobuf:"bytes,2,rep,name=battles" json:"battles,omitempty"`
	Chars            []*CharData_   `protobuf:"bytes,3,rep,name=chars" json:"chars,omitempty"`
	Mobs             []*CharData_   `protobuf:"bytes,4,rep,name=mobs" json:"mobs,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayDungeonAns) Reset()                    { *m = PlayDungeonAns{} }
func (m *PlayDungeonAns) String() string            { return proto.CompactTextString(m) }
func (*PlayDungeonAns) ProtoMessage()               {}
func (*PlayDungeonAns) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *PlayDungeonAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

func (m *PlayDungeonAns) GetBattles() []*BattleData_ {
	if m != nil {
		return m.Battles
	}
	return nil
}

func (m *PlayDungeonAns) GetChars() []*CharData_ {
	if m != nil {
		return m.Chars
	}
	return nil
}

func (m *PlayDungeonAns) GetMobs() []*CharData_ {
	if m != nil {
		return m.Mobs
	}
	return nil
}

// 캐릭터 렙벨업 요청
type LevelupCharReq struct {
	SlotNo           *uint32 `protobuf:"varint,1,req,name=slotNo" json:"slotNo,omitempty"`
	Vc1              *uint32 `protobuf:"varint,2,req,name=vc1" json:"vc1,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LevelupCharReq) Reset()                    { *m = LevelupCharReq{} }
func (m *LevelupCharReq) String() string            { return proto.CompactTextString(m) }
func (*LevelupCharReq) ProtoMessage()               {}
func (*LevelupCharReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *LevelupCharReq) GetSlotNo() uint32 {
	if m != nil && m.SlotNo != nil {
		return *m.SlotNo
	}
	return 0
}

func (m *LevelupCharReq) GetVc1() uint32 {
	if m != nil && m.Vc1 != nil {
		return *m.Vc1
	}
	return 0
}

// 캐릭터 렙벨업 결과
type LevelupCharAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	Char             *CharData_ `protobuf:"bytes,2,opt,name=char" json:"char,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LevelupCharAns) Reset()                    { *m = LevelupCharAns{} }
func (m *LevelupCharAns) String() string            { return proto.CompactTextString(m) }
func (*LevelupCharAns) ProtoMessage()               {}
func (*LevelupCharAns) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *LevelupCharAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

func (m *LevelupCharAns) GetChar() *CharData_ {
	if m != nil {
		return m.Char
	}
	return nil
}

// 캐릭터 티어 업 요청
type TierupCharReq struct {
	SlotNo           *uint32 `protobuf:"varint,1,req,name=slotNo" json:"slotNo,omitempty"`
	Vc2              *uint32 `protobuf:"varint,2,req,name=vc2" json:"vc2,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TierupCharReq) Reset()                    { *m = TierupCharReq{} }
func (m *TierupCharReq) String() string            { return proto.CompactTextString(m) }
func (*TierupCharReq) ProtoMessage()               {}
func (*TierupCharReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *TierupCharReq) GetSlotNo() uint32 {
	if m != nil && m.SlotNo != nil {
		return *m.SlotNo
	}
	return 0
}

func (m *TierupCharReq) GetVc2() uint32 {
	if m != nil && m.Vc2 != nil {
		return *m.Vc2
	}
	return 0
}

// 캐릭터 렙벨업 결과
type TierupCharAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=MSG.ErrorCode" json:"err,omitempty"`
	Char             *CharData_ `protobuf:"bytes,2,opt,name=char" json:"char,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *TierupCharAns) Reset()                    { *m = TierupCharAns{} }
func (m *TierupCharAns) String() string            { return proto.CompactTextString(m) }
func (*TierupCharAns) ProtoMessage()               {}
func (*TierupCharAns) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *TierupCharAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

func (m *TierupCharAns) GetChar() *CharData_ {
	if m != nil {
		return m.Char
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentsNot)(nil), "MSG.ContentsNot")
	proto.RegisterType((*PlayDungeonNot)(nil), "MSG.PlayDungeonNot")
	proto.RegisterType((*PlayDungeonNot_DungeonPlay)(nil), "MSG.PlayDungeonNot.DungeonPlay")
	proto.RegisterType((*OwnedCharacterNot)(nil), "MSG.OwnedCharacterNot")
	proto.RegisterType((*CreateCharReq)(nil), "MSG.CreateCharReq")
	proto.RegisterType((*CreateCharAns)(nil), "MSG.CreateCharAns")
	proto.RegisterType((*CurrencyNot)(nil), "MSG.CurrencyNot")
	proto.RegisterType((*PlayDungeonReq)(nil), "MSG.PlayDungeonReq")
	proto.RegisterType((*PlayDungeonAns)(nil), "MSG.PlayDungeonAns")
	proto.RegisterType((*LevelupCharReq)(nil), "MSG.LevelupCharReq")
	proto.RegisterType((*LevelupCharAns)(nil), "MSG.LevelupCharAns")
	proto.RegisterType((*TierupCharReq)(nil), "MSG.TierupCharReq")
	proto.RegisterType((*TierupCharAns)(nil), "MSG.TierupCharAns")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0x1f, 0x55, 0xf7, 0xc6, 0x86, 0x75, 0x1e, 0x24, 0x14, 0xc1, 0x30, 0x08, 0x2e, 0x3e,
	0x04, 0xba, 0xe2, 0xc3, 0xfa, 0xe6, 0x66, 0x65, 0x5f, 0xdc, 0x2a, 0xa9, 0xfa, 0xe2, 0x83, 0x4c,
	0xd3, 0x4b, 0x5b, 0x48, 0x66, 0xea, 0x64, 0x5a, 0xe9, 0x3f, 0xf2, 0x0f, 0xf8, 0xfb, 0x94, 0x99,
	0x49, 0xd3, 0x04, 0x6a, 0x89, 0xb0, 0x6f, 0xf7, 0x9e, 0x73, 0xe6, 0xce, 0x99, 0x7b, 0x06, 0x60,
	0xc1, 0x4a, 0x4c, 0xd6, 0x52, 0x28, 0x41, 0xbc, 0xbb, 0xe9, 0xed, 0xe8, 0x71, 0x2e, 0xca, 0x52,
	0x70, 0x0b, 0xd1, 0x6f, 0x10, 0xa4, 0x82, 0x2b, 0xe4, 0xaa, 0x9a, 0x08, 0x45, 0x46, 0xf0, 0x28,
	0xaf, 0xdb, 0xc8, 0x89, 0xbd, 0x8b, 0xb3, 0xac, 0xe9, 0xc9, 0x33, 0x38, 0x9b, 0x6f, 0xf8, 0x02,
	0x05, 0x9f, 0x88, 0xc8, 0x8d, 0xdd, 0x8b, 0x61, 0x76, 0x00, 0x08, 0x01, 0x5f, 0xad, 0x50, 0x46,
	0x9e, 0x21, 0x4c, 0x4d, 0xff, 0x38, 0x10, 0x7e, 0x2a, 0xd8, 0xee, 0x66, 0xaf, 0x52, 0xe4, 0x0d,
	0x0c, 0xd6, 0x05, 0xdb, 0xd9, 0xe9, 0xc1, 0xe5, 0xf3, 0xe4, 0x6e, 0x7a, 0x9b, 0x74, 0x35, 0x49,
	0x5d, 0x6a, 0x34, 0xb3, 0xea, 0xd1, 0x6f, 0x07, 0x82, 0x16, 0xdc, 0xf5, 0xe2, 0xfc, 0xcb, 0x8b,
	0x7b, 0xf0, 0x42, 0x5e, 0xc1, 0xc3, 0x19, 0x53, 0xaa, 0xc0, 0x2a, 0xf2, 0xcc, 0xd5, 0xe7, 0xe6,
	0xea, 0x6b, 0x83, 0xdd, 0x30, 0xc5, 0xbe, 0x67, 0x7b, 0x01, 0x79, 0x01, 0x83, 0x7c, 0xc9, 0x64,
	0x15, 0xf9, 0x46, 0x19, 0x1a, 0x65, 0xba, 0x64, 0xd2, 0xea, 0x2c, 0x49, 0x28, 0xf8, 0xa5, 0x98,
	0x55, 0xd1, 0xe0, 0xa8, 0xc8, 0x70, 0xf4, 0x0a, 0x9e, 0x7c, 0xfc, 0xc9, 0x71, 0xae, 0x71, 0x96,
	0x2b, 0x94, 0x7a, 0x07, 0xcd, 0x78, 0xe7, 0xc4, 0x78, 0xfa, 0x12, 0x86, 0xa9, 0x44, 0xa6, 0x50,
	0x33, 0x19, 0xfe, 0x20, 0x4f, 0xe1, 0x81, 0x66, 0x9a, 0x07, 0xd7, 0x1d, 0x1d, 0xb7, 0x85, 0xef,
	0x78, 0x45, 0x62, 0xf0, 0x50, 0x4a, 0xa3, 0x0a, 0xeb, 0xe9, 0xef, 0xa5, 0x14, 0x32, 0x15, 0x73,
	0xcc, 0x34, 0x45, 0x53, 0x08, 0xd2, 0x8d, 0x94, 0xc8, 0xf3, 0x9d, 0x36, 0x74, 0x0e, 0xde, 0x36,
	0x1f, 0xd7, 0x63, 0x75, 0x69, 0x91, 0xcb, 0x7a, 0x81, 0xba, 0xb4, 0xc8, 0xeb, 0x3a, 0x5e, 0x5d,
	0xd2, 0xeb, 0x4e, 0xb8, 0xda, 0xe1, 0x7f, 0xa7, 0x42, 0x7f, 0x75, 0x7f, 0x48, 0x2f, 0xf7, 0xed,
	0x28, 0xdd, 0xde, 0x51, 0x7a, 0x7d, 0xa2, 0xf4, 0x4f, 0x44, 0xf9, 0x16, 0xc2, 0x0f, 0xb8, 0xc5,
	0x62, 0xb3, 0x6e, 0x05, 0x52, 0x15, 0x42, 0x1d, 0x02, 0xb1, 0xdd, 0x7e, 0x9d, 0xcd, 0xf2, 0xc6,
	0xf4, 0x6b, 0xe7, 0x6c, 0xbf, 0x57, 0x52, 0xf0, 0xb5, 0xb9, 0xc8, 0x8d, 0x9d, 0x63, 0x9e, 0x34,
	0x47, 0xaf, 0x60, 0xf8, 0x79, 0x85, 0xb2, 0xa7, 0xa5, 0x76, 0x9e, 0xf4, 0x4b, 0xfb, 0xe8, 0xbd,
	0x39, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x25, 0xe0, 0x26, 0x81, 0x6f, 0x04, 0x00, 0x00,
}
